// Due to the grafana/ui Icon component making fetch requests to
// `/public/img/icon/<icon_name>.svg` we need to mock react-inlinesvg to prevent
// the failed fetch requests from displaying errors in console.
//
// This is a project-owned copy of `.config/jest/mocks/react-inlinesvg.tsx`. It lives
// outside `.config` because that folder is regenerated by `@grafana/create-plugin`
// scaffolding updates, which silently reset this file to a version that drops all
// props except `src` (breaking aria-label/role/click-handler forwarding used by
// @grafana/ui components such as Select's clear indicator). See jest.config.js
// moduleNameMapper override.

import { Ref } from 'react';

export default function InlineSVG({
  innerRef,
  cacheRequests,
  preProcessor,
  ...rest
}: {
  innerRef: Ref<SVGSVGElement>;
  cacheRequests: boolean;
  preProcessor: () => string;
}) {
  return <svg ref={innerRef} {...rest} />;
}
